apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "hyperopt.fullname" . }}-monitor
  labels:
    app.kubernetes.io/name: {{ include "hyperopt.name" . }}-monitor
    helm.sh/chart: {{ include "hyperopt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hyperopt.name" . }}c
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hyperopt.name" . }}-monitor
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          command:
            - monitor
          args: ["hyperopt-worker"]
          env:
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "hyperopt.name" . }}
                  key: aws_secret_access_key
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "hyperopt.name" . }}
                  key: aws_access_key_id
            - name: MONGO_DB_ADDRESS
              value: "{{ include "hyperopt.fullname" . }}-mongo{{ .Release.Namespace }}.svc.cluster.local"
            - name: MONGO_DB_PORT
              value: {{ .Values.mongo.port }}
            {{- range $key, $val := .Values.worker.env }}
            - name: {{ $key | upper }}
              value: {{ $val | quote }}
            {{- end}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
