{{- if .Values.mongo.ingress.enabled -}}
{{- $fullName := include "hyperopt.fullname" . -}}-mongo
{{- $ingressPath := .Values.mongo.ingress.path -}}-mongo
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-mongo
  labels:
    app.kubernetes.io/name: {{ include "hyperopt.name" . }}-mongo
    helm.sh/chart: {{ include "hyperopt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.mongo.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.mongo.ingress.tls }}
  tls:
  {{- range .Values.mongo.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.mongo.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}-mongo
              servicePort: http
  {{- end }}
{{- end }}
