kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "hyperopt.fullname" . }}-monitor
  labels:
    app.kubernetes.io/name: {{ include "hyperopt.name" . }}-monitor
    helm.sh/chart: {{ include "hyperopt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "hyperopt.fullname" . }}-monitor
roleRef:
  kind: Role
  namespace: {{ .Release.Namespace }}
  name: {{ include "hyperopt.fullname" . }}-monitor
  apiGroup: rbac.authorization.k8s.io

