{{- if .Values.worker.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyperopt.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ default "" $val | b64enc | quote }}
  {{- end}}
{{- end}}

