apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyperopt.name" . }}
type: Opaque
data:
  aws_secret_access_key: {{ template "aws_secret_access_key" . }}
  aws_access_key_id: {{ template "aws_access_key_id" . }}

