apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "hyperopt.fullname" . }}-mongo
  labels:
    app.kubernetes.io/name: {{ include "hyperopt.name" . }}-mongo
    helm.sh/chart: {{ include "hyperopt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
      protocol: TCP
      name: mongo
  selector:
    app.kubernetes.io/name: {{ include "hyperopt.name" . }}-mongo
    helm.sh/chart: {{ include "hyperopt.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

